<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="Rider29966.Default" %>
<%@ MasterType TypeName="Rider29966.Codes.MyMaster" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <p>See demo solution <a href="https://youtrack.jetbrains.com/issue/RIDER-29966">RIDER-29966</a>.</p>
    <p>You can check commits of file <em>Default.aspx.designer.cs</em> generated by 
        <ul>
            <li><a href="https://github.com/bambuca/Rider29966/blob/dec8732ede37e6227fd02b2168ae3c7b88aced9e/RIDER-29966/Default.aspx.designer.cs">Visual Studio 2019 (v 16.8.3)</a> - Property Master is of type <em>MyMaster</em> (it's OK)</li>
            <li><a href="https://github.com/bambuca/Rider29966/blob/e50b29b6dce122a8d14ab988edacffdd9079caa0/RIDER-29966/Default.aspx.designer.cs">Rider 2020.3.2</a> - Property Master is of type <em>Site</em> (it's BAD)</li>
        </ul>
    You can also check the <a href="https://github.com/bambuca/Rider29966/commit/e50b29b6dce122a8d14ab988edacffdd9079caa0">diff</a>.
</asp:Content>
