<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="Rider29966.Default" %>
<%@ MasterType TypeName="Rider29966.Codes.MyMaster" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <p>See <a href="https://youtrack.jetbrains.com/issue/RIDER-29966">RIDER-29966</a></p>
    <p>You can check commits of file <em>Default.aspx.designer.cs</em> generated by 
        <ul>
            <li><a href="TBD">Visual Studio 2019 (v 16.8.3)</a></li>
            <li><a href="TBD">Rider 2020.3.2</a></li>
        </ul>
</asp:Content>
