//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rider29966
{


    public partial class Default
    {

        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Rider29966.Codes.MyMaster Master
        {
            get
            {
                return ((Rider29966.Codes.MyMaster)(base.Master));
            }
        }
    }
}
